### ISSUE TITLE
Background display error

### ISSUE THREAD

**Issue by hongfeiyucode** [Arefnue/NueDeck#2]
mac m1 
2- Combat Scene

<img width="255" alt="image" src="https://user-images.githubusercontent.com/16367679/195983225-7b190541-6c9c-4ab6-b334-3c534765f5f5.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/16367679/195983109-084a7e99-2092-454c-85b4-0f4e654f91a4.png">

<img width="214" alt="image" src="https://user-images.githubusercontent.com/16367679/195983238-b69797b9-46ee-4049-8fb1-c92193d9ab52.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/16367679/195983376-e9839aad-477c-4a55-b43b-3843637b153d.png">

**Comment by Arefnue** [comment]
Wow, thats very interesting issue. I don not have mac and can not test this issue properly but I will investigate. I just simply use default sprites with default shaders.

**Comment by hongfeiyucode** [comment]
> Wow, thats very interesting issue. I don not have mac and can not test this issue properly but I will investigate. I just simply use default sprites with default shaders.

Thank you very much!

**Comment by hongfeiyucode** [comment]
Win10 

<img width="452" alt="image" src="https://user-images.githubusercontent.com/16367679/196081622-6d31a441-d897-49cd-8a07-8c1ba9ba3bac.png">

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/16367679/196081554-b5f8c526-e4e2-4eec-a29d-09d47dcc538c.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/16367679/196081989-aabfe1c4-1a34-4c4f-9bc7-6e7e662afa9f.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/16367679/196081924-153a1c2e-2915-4df6-980f-e4c704571acd.png">

<img width="479" alt="image" src="https://user-images.githubusercontent.com/16367679/196082646-eedf466f-31be-41cf-a17d-39bf33dd90ec.png">


<img width="1108" alt="image" src="https://user-images.githubusercontent.com/16367679/196082593-9542fc74-10a6-4bee-8e14-56978260e76a.png">

**Comment by hongfeiyucode** [comment]
My installation method on win and mac is **git clone**.
By the way, unity asset store has the same problem.

**Comment by latedude2** [comment]
I had the same issue and setting Anti-aliasing to FXAA on Main Camera fixes the issue for me. No idea why, but it works 🤷

**Comment by Arefnue** [comment]
> I had the same issue and setting Anti-aliasing to FXAA on Main Camera fixes the issue for me. No idea why, but it works 🤷

Thank you! I couldn't figure it out because it didn't happen to me. Thank you for your contribution.

**Comment by mogocat** [comment]
Same error. Fixed by upgrade to unity 2022
